# Railway configuration for Olivia Backend
# URGENT: Force Railway to detect changes

[build]
builder = "dockerfile"

[deploy]
startCommand = "npm run start:debug"
healthcheckPath = "/health"
healthcheckTimeout = 300 