# Railway configuration for Olivia Backend
# URGENT: Force Railway to detect changes
# Last update: 2025-01-08 18:30

[build]
builder = "dockerfile"

[deploy]
startCommand = "npm run start:railway"
healthcheckPath = "/health"
healthcheckTimeout = 300 